### ISSUE TITLE
Draft emails for V3 launch

### ISSUE THREAD

**Issue by misaugstad** [manaswis/cmsc634_sidewalk-mTurk#14]
Initial draft:
- [x] Generic inviting for participation
- [x] Promotional ("will you promote for us") -- this should just require an extra bit at the top
- [x] Rekindling with people who have contacted us before
- [x] Volunteers who have _used_ the tool
- [x] Manaswi's first pass to edit
- [x] Teja's first pass to edit
- [x] Mikey's first pass to edit

[Draft emails doc here](https://docs.google.com/document/d/10fPLQlBQF2joPh6OQJ1TsjdTQ8OfzRr-zM-HKEe1P68/edit)

**Comment by misaugstad** [comment]
I am having trouble remembering what was said at the meeting regarding rekindling emails. Is that super personalized, or did we decide that there was some sort of boilerplate thing that would be said to each, and customized from there?

**Comment by manaswisaha** [comment]
I think some boilerplate (for helping us promote maybe)  and some
customization based on the email they sent.


Best Regards,
Manaswi Saha
Ph.D. Student
Department of Computer Science
University of Maryland, College Park
http://cs.umd.edu/~manaswi/
Twitter - @manaswisaha <https://twitter.com/manaswisaha>

**Comment by maddalihanumateja** [comment]
We need subject lines as well. Added some temporary ones.
