### ISSUE TITLE
Combine contacts spreadsheet tabs

### ISSUE THREAD

**Issue by misaugstad** [manaswis/cmsc634_sidewalk-mTurk#15]
[link to spreadsheet](https://docs.google.com/spreadsheets/d/13NhzF7SBUqCvPDxZnd9f1bkzfzAGxC21AWStX5wRd9o/edit#gid=143381425)

This involves deciding on deciding on a set of columns that can be used across all the entries.

**Comment by maddalihanumateja** [comment]
Have created a tab called "master list" on the spreadsheet with the combined information.
We may need to 
- delete some entries (The huge list of DC Advisory Neighborhood Commission emails).
- add columns (categories like "need to initiate contact","need to reestablish contact")
- resolve some ambiguous column data (status: "sent"?)
I'll create a separate spreadsheet for social media entities to contact
