### ISSUE TITLE
Categorize responses from previous contacts

### ISSUE THREAD

**Issue by misaugstad** [manaswis/cmsc634_sidewalk-mTurk#16]
[link](https://docs.google.com/document/d/1e-Z9k2NL7hdgN2MZC8zIjwMohBl-xz7pta9vjCHQXnk/edit)

city govts, people contacting/showing interest

**Comment by maddalihanumateja** [comment]
Categories
1. Individuals:
2. Organizations
  i. Government
  ii. NGO
  iii. Corporation

**Comment by maddalihanumateja** [comment]
Its fine long as the final result is a csv where one of the columns is an email address. The rest of the fields can be combined to filter untargeted segments.
