### ISSUE TITLE
Brainstorm tasks for summer undergrads

### ISSUE THREAD

**Issue by misaugstad** [manaswis/cmsc634_sidewalk-mTurk#18]
We could compile a list of Github issues on the main SidewalkWebpage repo that would be good for them to do to get off the ground.

TODO: Go over the tasks and select some of the issues that can be undergrad projects. Potential projects are marked with the label ['potential-intern-assignment'](https://github.com/ProjectSidewalk/SidewalkWebpage/issues?q=is%3Aopen+is%3Aissue+label%3Apotential-intern-assignment)

**Comment by manaswisaha** [comment]
Here is the google doc for this - https://docs.google.com/document/d/1NYtjteOWac7fZ-G3p8f69Iw8Wt3F-MYv7gE6aSimglc/edit?ts=59038fc2#
