### ISSUE TITLE
Implement a HIT

### ISSUE THREAD

**Issue by manaswisaha** [manaswis/cmsc634_sidewalk-mTurk#2]
Implement the workflow for an mTurk HIT:

1. When the user goes to the HIT page,
    1.1 Show the HIT intro page. Turker has to Accept HIT at this point.
         1.1.1 Track the page visit of each step
    1.2 On clicking Accept HIT, show the onboarding screen if the turker hasn't taken it
          1.2.1 Get that information from the turker table
          1.2.2 Get worker ID, assignment ID and other mTurk related information and store it in the database in this step [From @maddalihanumateja]
    1.3 If onboarding is done previously or turker is revisiting, show the audit screen
2. When the user goes to the audit page, create a HIT (a mission of some distance)
    2.1 The streets can be repeated across missions if it hasn't been audited by x turkers
3. At the end of the mission, 
      3.1 Show a mission completion dialog with Complete button.  
      3.2 Send mTurk a complete HIT message (which necessary information) on click of the Complete button [From @maddalihanumateja]

**Comment by misaugstad** [comment]
Is there any work left to do on this? I am under the impression that all we have left is backend stuff (loading the correct routes), so is all the stuff mentioned here done?

**Comment by maddalihanumateja** [comment]
This looks like pretty old stuff. It's been overhauled
