### ISSUE TITLE
Look into mail services other than MailChimp & Constant Contact

### ISSUE THREAD

**Issue by misaugstad** [manaswis/cmsc634_sidewalk-mTurk#20]

**Comment by maddalihanumateja** [comment]
- [x] MailChimp has a pay as you go method as well ($9 per 300 "credits"). Can remove the mailchimp footer in this
- [x] Constant Contact has monthly payment and no a/b testing
- [x] Emma (Phone call before the actual free tour) (1 year agreement, the caller suggested that emma might not be the best choice given our requirements (brief campaign)) 
- [x] SendinBlue (Checks if your mail goes into the inbox of a list of email providers: gmail, yahoo, comcast, orange, aol). Extra verification of account before sending a campaign or adding contacts. No a/b testing. Any additional features need signup with partners (analytics). $40 to upgrade for without footer.
- [x] AWeber needs credit card info for signup
