### ISSUE TITLE
Use new tables to get labels from only our experiment

### ISSUE THREAD

**Issue by misaugstad** [manaswis/cmsc634_sidewalk-mTurk#9]
When we do our label clustering and analysis, we need to either only query the database for those particular labels that pertain to our experiment, or we can query for all labels and then subset them based on those tables.

**Comment by misaugstad** [comment]
@maddalihanumateja Which table(s) do I need to look at? Essentially all I need is to know labels came from our experiment. This could be from having the label_id, the street_edge_id, the route_id, or anything else that is identifying since I can link them all to label_id anyway.

**Comment by maddalihanumateja** [comment]
@misaugstad this is a conversation you need to have with @manaswis. I think the amt_assignment table performs the same function as the audit_task table for this project. I'm also assuming that assignment_id would be equivalent to audit_task_id to map labels to their respective assignments

**Comment by manaswisaha** [comment]
@misaugstad @maddalihanumateja amt_assignment doesn't have the same role coz it tracks the assignment to one HIT while audit_task tracks each task (i.e. street segment) within each HIT.

For labels for this experiment, you need to use 3 tables - amt_assignment -> audit_task -> labels

So each audit_task also has an amt_assignment id, and each audit task id links to the labels in the labels table. You can use these 3 ids to track the turker labels.
